import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-unapplied-cash-credit-balance-recovery",
  "engine": "recovery",
  "title": "Unapplied Cash & Customer Credit Recovery",
  "shortTitle": "Unapplied Cash and Customer Credit Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through unapplied cash & customer credit recovery",
  "industry": "Cash Application Operations",
  "uiPort": 4636,
  "apiPort": 5636,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Unapplied Cash & Customer Credit Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "appliedCash",
    "expectedKey": "availableCash",
    "actualLabel": "Applied and Resolved Cash",
    "expectedLabel": "Available Cash and Credits",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Unapplied Cash & Customer Credit Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("bank-lockbox-ingestion","UCC01","Bank lockbox ingestion","Execute bank lockbox ingestion using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed bank lockbox ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Bank lockbox ingestion Reference","text","UCC01-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("customer-payer-normalization","UCC02","Customer payer normalization","Execute customer payer normalization using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed customer payer normalization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Customer payer normalization Reference","text","UCC02-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("remittance-extraction","UCC03","Remittance extraction","Execute remittance extraction using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed remittance extraction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Remittance extraction Reference","text","UCC03-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("invoice-candidate-matching","UCC04","Invoice candidate matching","Execute invoice candidate matching using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed invoice candidate matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Invoice candidate matching Reference","text","UCC04-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("exact-cash-matching","UCC05","Exact cash matching","Execute exact cash matching using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed exact cash matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Exact cash matching Reference","text","UCC05-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("probabilistic-cash-matching","UCC06","Probabilistic cash matching","Execute probabilistic cash matching using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed probabilistic cash matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Probabilistic cash matching Reference","text","UCC06-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("partial-payment-allocation","UCC07","Partial payment allocation","Execute partial payment allocation using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed partial payment allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Partial payment allocation Reference","text","UCC07-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("consolidated-payment-handling","UCC08","Consolidated payment handling","Execute consolidated payment handling using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed consolidated payment handling decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Consolidated payment handling Reference","text","UCC08-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("deduction-identification","UCC09","Deduction identification","Execute deduction identification using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed deduction identification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Deduction identification Reference","text","UCC09-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("unidentified-receipt-workflow","UCC10","Unidentified receipt workflow","Execute unidentified receipt workflow using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed unidentified receipt workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Unidentified receipt workflow Reference","text","UCC10-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("customer-credit-analysis","UCC11","Customer credit analysis","Execute customer credit analysis using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed customer credit analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Customer credit analysis Reference","text","UCC11-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("refund-reapplication-control","UCC12","Refund reapplication control","Execute refund reapplication control using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed refund reapplication control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Refund reapplication control Reference","text","UCC12-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("general-ledger-reconciliation","UCC13","General-ledger reconciliation","Execute general-ledger reconciliation using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed general-ledger reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","General-ledger reconciliation Reference","text","UCC13-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("aging-escalation","UCC14","Aging escalation","Execute aging escalation using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed aging escalation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Aging escalation Reference","text","UCC14-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]}),
feature("customer-unit-analytics","UCC15","Customer unit analytics","Execute customer unit analytics using bank accounts, lockboxes, customers, payers, remittances, invoices, partial payments, consolidated receipts, deductions, unidentified cash, credits, refunds, and GL balances.","Produce a governed customer unit analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Business Unit / Cash Population","text","Business Unit / Cash Population · Standard Case"],["caseReference","Customer unit analytics Reference","text","UCC15-2026-001"],["appliedCash","Applied and Resolved Cash","currency",1252500],["availableCash","Available Cash and Credits","currency",1477950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"appliedCash",subjects:["Bank lockbox ingestion case","Customer payer normalization case","Remittance extraction case","Invoice candidate matching case","Exact cash matching case"]})
]);
